const fs = require('fs');
const path = require('path');
const assert = require('assert');
const { spawnSync } = require('child_process');
const root = path.join(__dirname, '..');
const files = [];
(function walk(dir){ for(const entry of fs.readdirSync(dir,{withFileTypes:true})){ const full=path.join(dir,entry.name); entry.isDirectory()?walk(full):entry.name.endsWith('.js')&&files.push(full); } })(path.join(root,'src'));
for(const file of files){ const result=spawnSync(process.execPath,['--check',file],{encoding:'utf8'}); assert.equal(result.status,0,`${file}: ${result.stderr}`); }
const source = fs.readFileSync(path.join(root,'src','tampermonkey','hua-yi-helper.user.js'),'utf8');
const all = files.map(f=>fs.readFileSync(f,'utf8')).join('\n');
assert(!/ghp_[A-Za-z0-9]{20,}/.test(all));
assert(!/(?:username|password|token)\s*[:=]\s*['"][A-Za-z0-9+/_-]{20,}['"]/i.test(all));
assert(!new RegExp('playback'+'Rate','i').test(all));
assert(!new RegExp('--'+'speed\\b','i').test(all));
assert(!/currentTime\s*=/.test(all));
assert(!/window\.open\s*=/.test(source));
assert(!/removeAttribute\(['"]on/.test(source));
assert(!/@require\s/.test(source));
const playerStart=source.indexOf('function handlePlayer()');
const playerEnd=source.indexOf('var VERIFIED',playerStart);
const player=source.slice(playerStart,playerEnd);
assert(player && /playerMediaStatus/.test(player) && /findPlayerPrompt/.test(player));
assert(/media\.video\.play\(\)/.test(player));
assert(!/currentTime\s*=/.test(player));
const pkg=JSON.parse(fs.readFileSync(path.join(root,'package.json'),'utf8'));
assert.equal((source.match(/@version\s+(\S+)/)||[])[1],pkg.version);
console.log(`v8 源码质量检查通过：${files.length} 个 JavaScript 文件`);
